[app]

title = "VPSToolKit - VPS 服务统一管理脚本"
splash = """

██╗   ██╗██████╗ ███████╗████████╗ ██████╗  ██████╗ ██╗     ██╗  ██╗██╗████████╗
██║   ██║██╔══██╗██╔════╝╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██║ ██╔╝██║╚══██╔══╝
██║   ██║██████╔╝███████╗   ██║   ██║   ██║██║   ██║██║     █████╔╝ ██║   ██║   
╚██╗ ██╔╝██╔═══╝ ╚════██║   ██║   ██║   ██║██║   ██║██║     ██╔═██╗ ██║   ██║   
 ╚████╔╝ ██║     ███████║   ██║   ╚██████╔╝╚██████╔╝███████╗██║  ██╗██║   ██║   
  ╚═══╝  ╚═╝     ╚══════╝   ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝   
                                                                                  
"""
splash_timeout = 500 # ms
entry = 'main'

[local]
include = [
    '/etc/vpstoolkit/modules.d/default/*.toml',
    '/etc/vpstoolkit/modules.d/extend/*.toml',
]

[remote]
subscribes = [
    # remote urls
]
