[scripts]
# 系统工具脚本

# BBR 加速
system_bbr = "scripts/system/bbr.sh"

# DD 重装系统
system_dd = "scripts/system/dd.sh"


[[menus]]
id = "system"
title = "系统工具"
sub_menus = [
    "system_bbr",
    "system_dd",
]

[[menu]]
id = "system_bbr"
title = "BBR 加速管理"
script = "system_bbr"

[[menu]]
id = "system_dd"
title = "DD 重装系统"
script = "system_dd"
