[scripts]
# 实用工具脚本

# Speedtest 网络测速
tools_speedtest = "scripts/tools/speedtest.sh"


[[menus]]
id = "tools"
title = "实用工具"
sub_menus = [
    "tools_speedtest",
]

[[menu]]
id = "tools_speedtest"
title = "Speedtest 网络测速"
script = "tools_speedtest"
